# PowerShell script to set up .env file for password creation
# This script will help you create the .env file with your Supabase credentials

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Supabase Environment Setup" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if (Test-Path .env) {
    $overwrite = Read-Host ".env file already exists. Overwrite? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Cancelled." -ForegroundColor Yellow
        exit
    }
}

Write-Host "Please provide your Supabase credentials:" -ForegroundColor Yellow
Write-Host "(You can find these in Supabase Dashboard > Settings > API)" -ForegroundColor Gray
Write-Host ""

# Get Supabase URL
$supabaseUrl = Read-Host "Enter your Supabase URL (e.g., https://xxxxx.supabase.co)"
if ([string]::IsNullOrWhiteSpace($supabaseUrl)) {
    Write-Host "Error: Supabase URL is required" -ForegroundColor Red
    exit 1
}

# Get Service Role Key
Write-Host ""
Write-Host "⚠️  IMPORTANT: You need the SERVICE_ROLE key, NOT the anon key!" -ForegroundColor Yellow
Write-Host "   The service_role key is found in the same API settings page." -ForegroundColor Gray
Write-Host ""
$serviceRoleKey = Read-Host "Enter your Supabase SERVICE_ROLE_KEY" -AsSecureString
$serviceRoleKeyPlain = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($serviceRoleKey)
)

if ([string]::IsNullOrWhiteSpace($serviceRoleKeyPlain)) {
    Write-Host "Error: Service Role Key is required" -ForegroundColor Red
    exit 1
}

# Create .env file
$envContent = @"
# Supabase Configuration
# Generated by setup-env.ps1

# Supabase Project URL
NEXT_PUBLIC_SUPABASE_URL=$supabaseUrl
SUPABASE_URL=$supabaseUrl

# Supabase Service Role Key (for admin operations)
SUPABASE_SERVICE_ROLE_KEY=$serviceRoleKeyPlain
"@

try {
    $envContent | Out-File -FilePath .env -Encoding utf8 -NoNewline
    Write-Host ""
    Write-Host "✅ .env file created successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "You can now run: node scripts/create-all-passwords.js" -ForegroundColor Cyan
} catch {
    Write-Host ""
    Write-Host "❌ Error creating .env file: $_" -ForegroundColor Red
    exit 1
}
